### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_GPS#68]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_gps.py:78
- [ ] adafruit_gps.py:89
- [ ] adafruit_gps.py:95
- [ ] adafruit_gps.py:101
- [ ] adafruit_gps.py:107
- [ ] adafruit_gps.py:114
- [ ] adafruit_gps.py:122
- [ ] adafruit_gps.py:206
- [ ] adafruit_gps.py:288
- [ ] adafruit_gps.py:326
- [ ] adafruit_gps.py:331
- [ ] adafruit_gps.py:396
- [ ] adafruit_gps.py:416
- [ ] adafruit_gps.py:442
- [ ] adafruit_gps.py:485
- [ ] adafruit_gps.py:534
- [ ] adafruit_gps.py:572
- [ ] adafruit_gps.py:650
- [ ] adafruit_gps.py:662
- [ ] adafruit_gps.py:678

**Comment by theendlessriver13** [comment]
I had a look at this, because I though it would make it much easier to implement the tests in #69 . However it turns out, some major refactoring has to be done to make this type safe. If anyone wants to continue on this, I pushed the changes I already did to this branch: https://github.com/theendlessriver13/Adafruit_CircuitPython_GPS/tree/type-annotations .

The main thing which causes problems, is the `data` lists having a variable length depending on the type of data. Ideally each sentence type would be a strongly typed named tuple (not sure if this is available on all boards?) for each sentence type or there would be one `Data` named tuple with all possible paramters most of them being `Optional`, so one would only have to check if it was None, not if it was a string, integer or float all the time ...

Also many, many checks for `is None` are missing to make this type safe...

The inherited class also causes some trouble:
`adafruit_gps.py:700: error: Return type "None" of "write" incompatible with return type "int" in supertype "GPS"`
